################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &OrgC
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrgCMSP

        # ID to load the MSP definition as
        ID: OrgCMSP

        MSPDir: ../crypto-config-orgc/peerOrganizations/orgc.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrgCMSP.admin', 'OrgCMSP.peer', 'OrgCMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrgCMSP.admin', 'OrgCMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrgCMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer1.orgc.example.com
              Port: 7051
